apiVersion: v1
kind: Secret
metadata:
  name: aws-configure
  labels:
    env: aws-secrets
stringData:
  AWS_ACCESS_KEY_ID: my-secet-acess-id-in-string-format
  AWS_SECRET_ACCESS_KEY: my-secret-access-key-in-string-format
type: Opaque
